package it.unipv.payroll.model;

import java.io.Serializable;
import java.text.ParseException;
import java.util.Calendar;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import it.unipv.payroll.util.TimeManagUtil;

@SuppressWarnings("serial")
@Entity
@Table

/*
 * Service Charges are assessed by Union for specific services given to the
 * Employee. Being so, they are forced to keep memory of the Employee which has
 * to pay and the Union that gets the payment. Each Service Charge contains the
 * autogenerated id, the name of the service, the time the Employee has used
 * this service and the cost of the charge.
 */

public class ServiceCharge implements Serializable {

	@Id	@GeneratedValue(strategy = GenerationType.AUTO)
	int ChargeID;
	String Service;
	@Temporal(TemporalType.TIMESTAMP)
	Calendar TimeStamp;
	float ChargeAmount;
	@ManyToOne	@JoinColumn(name = "union_id")
	Union union;
	@ManyToOne	@JoinColumn(name = "employee_id")
	Employee employee;

	public ServiceCharge() {
		super();
	}

	public ServiceCharge(float chargeAmount, String service, String timestamp) throws ParseException {
		super();
		ChargeAmount = chargeAmount;
		Service = service;
		TimeStamp = TimeManagUtil.getGCobjectfromString(timestamp);
	}

	// getters and setters

	public float getChargeAmount() {
		return ChargeAmount;
	}

	public void setChargeAmount(float chargeAmount) {
		ChargeAmount = chargeAmount;
	}

	public int getChargeID() {
		return ChargeID;
	}

	public String getService() {
		return Service;
	}

	public void setService(String service) {
		Service = service;
	}

	public String getTimeStamp() {
		return TimeManagUtil.getStringfromGCobject(TimeStamp);
	}

	public void setTimeStamp(String timestamp) throws ParseException {
		this.TimeStamp = TimeManagUtil.getGCobjectfromString(timestamp);
	}

	public Union getUnion() {
		return union;
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setUnion(Union union) {
		this.union = union;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

}
